[package]
name = "phenix"
version = "0.1.0"
authors = ["kazami <kazamizero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.cli]
path = "./cli"
